name: Verificar mensaje del último commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verificar mensaje del último commit
        uses: technote-space/conditional-value-for-github-action@v1.0.0
        with:
          value: '^(feat|fix|release)\('
          error-message: 'El mensaje del último commit no cumple con los requisitos.'
