name: Validate Commit Message

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate_commit_message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate commit message
      id: validate
      run: |
        commit_message=${{ github.event.commits[0].message }}
        if [[ $commit_message != *"feat"* && $commit_message != *"fix"* && $commit_message != *"release"* ]]; then
          echo "error: commit message does not contain 'feat', 'fix' or 'release'"
          exit 1
        fi
