name: Check commit message

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: commit-msg
        with:
          cond: ${{ contains(github.event.head_commit.message, 'feat(') || contains(github.event.head_commit.message, 'fix(') || contains(github.event.head_commit.message, 'release(') }}
          if_true: "true"
          if_false: "false"
      - name: Block merge if commit message is invalid
        if: steps.commit-msg.outputs.value == 'false'
        run: exit 1
      
