name: Inspect pull request
on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve commit messages
        id: retrieve_commits
        uses: atlwendy/retrieve-commit-messages-from-pr@v3
      - name: Check commit message
        id: check_message
        run: |
          commit_message=$(echo '${{ steps.retrieve_commits.outputs.commit_message }}')
          if [[ $commit_message == *"feat("* ]] || [[ $commit_message == *"fix("* ]] || [[ $commit_message == *"release("* ]]; then
            echo "::set-output name=valid::true"
          else
            echo "::set-output name=valid::false"
          fi
      - name: Conditional value for GitHub Action
        uses: haya14busa/action-cond@v1.0.0
        id: condval
        with:
          cond: ${{ steps.check_message.outputs.valid == 'true' }}
          if_true: "Commit message is valid"
          if_false: "error: Commit message doesn't include 'feat(', 'fix(' or 'release('"
      - name: Use conditional value
        run: echo "${{ steps.condval.outputs.value }}"
        if: failure()