name: Check commit message

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get last commit message
      id: get_commit
      run: |
        echo "::set-output name=message::$(git log -1 --pretty=%B)"

    - name: Check commit message
      id: check_commit
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ contains(steps.get_commit.outputs.message, 'feat(') || contains(steps.get_commit.outputs.message, 'fix(') || contains(steps.get_commit.outputs.message, 'release(') }}
        if_true: "merge allowed"
        if_false: "merge blocked"

    - name: Block merge if commit message does not contain 'feat(', 'fix(', or 'release('
      run: |
        if [ "${{ steps.check_commit.outputs.value }}" == "merge blocked" ]; then
          exit 1
        fi
