name: Semantic Versioning

on:
  push:
    branches:
      - 'release/*'
      - 'feat/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Last Branch and Semantic Version Containing String
        uses: ianwalter/get-last-branch-and-semantic-version-containing-string@v1
        with:
          regex-string: '^[0-9]+\.[0-9]+\.[0-9]+-(release|feat|fix)\/.*$'

      - name: Git Semantic Version (via branches)
        uses: iautom8things/semantic-version@v5
        with:
          tag_prefix: 'v'
          increment: 'commits'
          bump_each_commit: 'false'

      - name: Semantic Version Bump per Branch and Tag
        uses: mathieudutour/github-actions-semantic-version@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.VERSION }}

      - name: Set Version to 1.0.0 if no artifacts
        run: |
          if [ -z "$VERSION" ]; then
            echo "No artifacts found. Setting version to 1.0.0."
            VERSION="1.0.0"
          fi