name: Semantic Versioning

on:
  push:
    branches:
      - 'release/*'
      - 'feat/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release version
        uses: actions/github-script@v4
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            const latestRelease = releases[0];
            if (latestRelease) {
              console.log(`Latest release version: ${latestRelease.tag_name}`);
              return latestRelease.tag_name;
            } else {
              console.log('No releases found, setting version to 1.0.0');
              return '1.0.0';
            }
          outputs:
            version: ${{ steps.get_version.outputs.version }}

      - name: Determine version type
        id: determine_version_type
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ "$branch_name" == "release/"* ]]; then
            echo "major";
          elif [[ "$branch_name" == "feat/"* ]]; then
            echo "feat";
          elif [[ "$branch_name" == "fix/"* ]]; then
            echo "patch";
          fi
        shell: bash

      - name: Create new release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.determine_version_type.outputs.version }}-${{ github.sha }}
          release_name: Release ${{ steps.determine_version_type.outputs.version }}-${{ github.sha }}
          body: |
            Release ${{ steps.determine_version_type.outputs.version }}-${{ github.sha }}
          draft: false
          prerelease: false