name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Version Bumper
      uses: michmich112/version-bumper@v1.0.1
      with:
        options-file: "./.github/workflows/options.json"
        github-token: ${{ secrets.GITHUB_TOKEN }}
