name: Set Version

on: [push, pull_request]

jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        id: set_version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release/*" ]]; then
            echo "VERSION=major" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/feat/*" ]]; then
            echo "VERSION=feat" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/fix/*" ]]; then
            echo "VERSION=patch" >> $GITHUB_ENV
          else
            echo "VERSION=1.0.0" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact-name
          path: ./artifact
      - name: Set version from artifact
        id: set_version_from_artifact
        run: |
          exit_status=$?
          if [ $exit_status -eq 0 ]; then
            # Get the latest version from the artifact
            VERSION=$(ls -l ./artifact | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | sort -V | tail -n 1)
          else
            VERSION=${{ steps.set_version.outputs.VERSION }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
