name: Update version

on:
  push:
    branches:
      - 'release/*'
      - 'feat/*'
      - 'fix/*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update version
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/release/'* ]]; then
            echo "::set-env name=VERSION::$(echo ${{ env.VERSION }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
          elif [[ ${{ github.ref }} == 'refs/heads/feat/'* ]]; then
            echo "::set-env name=VERSION::$(echo ${{ env.VERSION }} | awk -F. '{$(NF-1) = $(NF-1) + 1;} 1' | sed 's/ /./g')"
          elif [[ ${{ github.ref }} == 'refs/heads/fix/'* ]]; then
            echo "::set-env name=VERSION::$(echo ${{ env.VERSION }} | awk -F. '{$(NF-2) = $(NF-2) + 1;} 1' | sed 's/ /./g')"
          fi
      - name: Save version
        run: |
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
