name: Semantic Versioning
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Semantic Version (via branches)
        uses: iautom8things/semantic-version@v5
        with:
          major_pattern: "^release/"
          minor_pattern: "^feat/"
          patch_pattern: "^fix/"