name: Semantic Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increment Semantic Version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        prerelease: false
