name: Semantic Versioning

on:
  push:
    branches:
      - 'release/*'
      - 'feat/*'
      - 'fix/*'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check if release exists
      id: check-release
      run: |
        version=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")
        echo "::set-output name=version::$version"
      continue-on-error: true

    - name: Set version
      id: set-version
      run: |
        branch_name=$(echo ${GITHUB_REF#refs/heads/})
        current_version="${{ steps.check-release.outputs.version }}"
        if [[ $branch_name == "release/"* ]]; then
          new_version="v$(( ${current_version#v} + 1 )).0.0"
        elif [[ $branch_name == "feat/"* ]]; then
          new_version="v${current_version#v.}.$(( ${current_version#v.} + 1 ))"
        elif [[ $branch_name == "fix/"* ]]; then
          new_version="v${current_version#v}.0.$(( ${current_version#v.0.} + 1 ))"
        else
          echo "Invalid branch name: $branch_name"
          exit 1
        fi
        echo "::set-output name=new_version::$new_version"
      continue-on-error: true

    - name: Create and push new tag
      if: success()
      run: |
        new_version="${{ steps.set-version.outputs.new_version }}"
        echo "Creating new tag: $new_version"
        git tag $new_version
        git push origin $new_version
