name: Bump version and create release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        MAJOR_STRING_TOKEN: "release("
        MINOR_STRING_TOKEN: "feat("
        PATCH_STRING_TOKEN: "fix("
        DEFAULT_BUMP: minor
