name: Semantic Versioning

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch tags
      run: git fetch --tags

    - name: Get latest tag
      id: get_tag
      run: echo "::set-output name=VERSION::$(git describe --tags --abbrev=0 2>/dev/null || echo '1.0.0')"

    - name: Set version
      run: echo "VERSION=${{ steps.get_tag.outputs.VERSION }}" >> $GITHUB_ENV
