name: Semantic Versioning

on:
  push:
    branches:
      - release/*
      - feat/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest artifact version
        id: get_version
        run: |
          # Get the latest artifact version
          version=$(ls -t artifacts/*.zip | head -n1 | sed 's/.*-\([0-9]\+\.[0-9]\+\.[0-9]\+\)\.zip/\1/')
          if [ -z "$version" ]; then
            # No artifact found, set version to 1.0.0
            echo "::set-output name=version::1.0.0"
          else
            # Artifact found, set version to the latest version
            echo "::set-output name=version::$version"
          fi

      - name: Set version
        id: set_version
        uses: PaulHatch/semantic-version@v5.2.1
        with:
          version: ${{ steps.get_version.outputs.version }}
          major: ${{ startsWith(github.ref, 'refs/heads/release/') }}
          minor: ${{ startsWith(github.ref, 'refs/heads/feat/') }}
          patch: ${{ startsWith(github.ref, 'refs/heads/fix/') }}

      - name: Use version
        run: |
          # Use the version in your build process
          echo "Using version ${{ steps.set_version.outputs.version }}"

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact-${{ steps.set_version.outputs.version }}.zip